# Generated by Django 4.2.5 on 2023-12-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('ticketNo', models.AutoField(primary_key=True, serialize=False)),
                ('customerPnr', models.CharField(max_length=100, null=True, unique=True)),
                ('pnrNo', models.CharField(max_length=100)),
                ('busNo', models.CharField(max_length=100, null=True)),
                ('issuedBy', models.CharField(max_length=100)),
                ('issueDate', models.DateTimeField(auto_now_add=True)),
                ('issueFrom', models.CharField(max_length=100, null=True)),
                ('travelDate', models.CharField(max_length=100)),
                ('timeSchedule', models.CharField(default='', max_length=100)),
                ('departure', models.CharField(default='', max_length=100)),
                ('destination', models.CharField(default='', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contactNo', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('seatNo', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busNo', models.CharField(max_length=100)),
                ('busType', models.CharField(choices=[('i10', 'i10'), ('Double Dacker', 'Double Dacker'), ('D45i', 'D44i')], default='i10', max_length=20)),
                ('registrationNo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Self', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=200)),
                ('notice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_No', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelDate', models.DateField()),
                ('timeSchedule', models.CharField(max_length=100)),
                ('distance', models.IntegerField()),
                ('pnrNo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price', models.FloatField(default=False)),
                ('busNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.bus')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='mainApp.city')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='mainApp.city')),
            ],
        ),
    ]
