# Generated by Django 4.2.5 on 2023-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_booked_pnrno'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='pnrNo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='price',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='booked',
            name='issueDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
